### ISSUE TITLE
Verschiedene Probleme, die ich am Code aktuellen Code finden konnte

### ISSUE THREAD

**Issue by henrybrink** [asm-team-2x2/chrome-dino#1]
Hallo Gruppe "2x2", ich hab ein paar Anmerkungen zu eurem Code:

Ich kann derzeit keine Sicherheitsüberprüfungen im Code finden, der gesammte Code läuft mit ROOT-RECHTEN!!!
Ich verstehe nicht, warum der Dinosaurier in der Luft ist - und ich mit einer Boje unterwegs bin? Was ist denn das für eine Pixelart? Die Kakteen sehen ehrlich gesagt auch eher wie beliebige Zylinder aus
Das Spiel ist unglaublich langsam, ich verstehe nicht warum das nicht schneller geht
Wenn ich 421x die Taste "3" drücke, stürzt das Programm OHNE JEDEN GRUND ab
Ich kann mit der Boje rückwärts gehen, aber nicht vorwärts
Der LCD-Bildschirm flackert
Es gibt keinen Highscore. WARUM SPIELE ICH DAS DUMME PROGRAMM DANN?
Wenn ich mich mind. 666 hintereinander ducke, dann explodiert die Mikrocontroller??? Ist das expected Behavior?
Ich habe das Spiel auf einer Flugreise nach Kanada mitgenommen, dort wurde das Spiel als eine "Beleidigung für die Bevölkerung" gesehen und ich wurde zu einer HAFTSTRAFE von 41 JAHREN auf Bewährung verurteilt

**Comment by benedictweis** [comment]
Also sowas aber auch, sehr unangebracht!
